#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const DAYS = parseInt(process.argv[2] || '7', 10);
if (isNaN(DAYS) || DAYS < 1) {
  console.error('Usage: node scripts/clean-reports.js [days]  (default: 7)');
  process.exit(1);
}

const CUT_MS = DAYS * 24 * 60 * 60 * 1000;
const NOW = Date.now();

const TARGET_DIRS = [
  path.join(process.cwd(), 'reports', 'ai-insights'),
  path.join(process.cwd(), 'cypress', 'screenshots', 'ai-analysis'),
];

// Session folder names are YYYYMMDD-HHmm-xxxx (generated by makeSessionId in cypress.config.js)
const SESSION_RE = /^(\d{4})(\d{2})(\d{2})-(\d{2})(\d{2})-[a-z0-9]{4}$/;

function parseSessionDate(name) {
  const m = SESSION_RE.exec(name);
  if (!m) return null;
  const [, y, mo, d, h, mi] = m;
  return new Date(`${y}-${mo}-${d}T${h}:${mi}:00`).getTime();
}

let removed = 0;
let kept = 0;

for (const base of TARGET_DIRS) {
  if (!fs.existsSync(base)) continue;
  const entries = fs.readdirSync(base, { withFileTypes: true });
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const ts = parseSessionDate(e.name);
    if (ts === null) continue; // skip non-session entries (e.g. latest.html lives next to these)
    const ageMs = NOW - ts;
    if (ageMs > CUT_MS) {
      const full = path.join(base, e.name);
      console.log(`  removing  ${full}`);
      fs.rmSync(full, { recursive: true, force: true });
      removed++;
    } else {
      kept++;
    }
  }
}

const plural = n => n === 1 ? 'folder' : 'folders';
console.log(`\nDone. Removed ${removed} ${plural(removed)} older than ${DAYS} day(s), kept ${kept}.`);
